name: "Extracting values and logging"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'    # every day at midnight

env:
  IMAGE_NAME_STAGE: air-analytics-dump:stage
  IMAGE_NAME_PROD: air-analytics-dump:prod

jobs:
  extract-names:
    runs-on: ubuntu-latest

    steps:
        - name: 'Check net 7'
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: 7.x

        - name: Fetch possible Stage-route through TestBB-lookup
          id: http-request-stage
          run: |
              response=$(curl -s "https://cloud.caspeco.se/.where?system=se_broupp")
              echo "Got response $response"
              echo "DEV_URL=$response" >> $GITHUB_ENV

        - name: Extract Stage branch name
          id: extract-stage-branch
          run: |
              response="${{ env.DEV_URL }}"
              echo "Got response: $response"
              if [[ $response != *"dev-"* ]]; then
              branch_name=$(echo "$response" | awk -F 'marc-|\\.azure' '{print $2}' | grep -oE '[0-9-]+[0-9]')
              echo "I parsed the branch_name: $branch_name"
              echo "BRANCH_NAME_PROD=$branch_name" >> $GITHUB_ENV
              echo "CHECKOUT_FAILED_STAGE=false" >> $GITHUB_ENV
              else
              echo "Branch name not found in $response."
              echo "BRANCH_NAME_STAGE=$branch_name" >> $GITHUB_ENV
              echo "CHECKOUT_FAILED_STAGE=true" >> $GITHUB_ENV
              fi
              echo "Direct variable in-step (branch_name): $branch_name"
              echo "Env var in-step (BRANCH_NAME_PROD): $BRANCH_NAME_PROD"
              echo "Env var in-step (BRANCH_NAME_STAGE): $BRANCH_NAME_STAGE"
              echo "Env var in-step (CHECKOUT_FAILED_STAGE): $CHECKOUT_FAILED_STAGE"

        - name: Read output
          id: read-output
          run: |           
            echo "Direct variable cross-steps (branch_name): $branch_name"
            echo "Env var cross-step (BRANCH_NAME_PROD): $BRANCH_NAME_PROD"
            echo "Env var cross-step (BRANCH_NAME_STAGE): $BRANCH_NAME_STAGE"
            echo "Env var cross-step (CHECKOUT_FAILED_STAGE): $CHECKOUT_FAILED_STAGE"

  use-vars:
    needs: extract-names
    runs-on: ubuntu-latest
        
    steps:
      - name: "print vars"
        id: "print-vars"
        run: |
            echo "Direct variable cross-job (branch_name): $branch_name"
            echo "Env var cross-job (BRANCH_NAME_PROD): $BRANCH_NAME_PROD"
            echo "Env var cross-job (BRANCH_NAME_STAGE): $BRANCH_NAME_STAGE"
            echo "Env var cross-job (CHECKOUT_FAILED_STAGE): $CHECKOUT_FAILED_STAGE"
